# Curated seed artists organised by genre.
# Each entry has a name and a list of related artists (used to pre-compute similarity).

SEED_GENRES = [
    "Pop", "Rock", "Electronic", "Hip-Hop", "R&B", "Indie",
    "Jazz", "Metal", "Classical", "Country", "Latin", "K-Pop",
    "Folk", "Blues", "Alternative", "Soul", "Funk", "Ambient",
]

# genre → list of {name, related}
SEED_ARTISTS_BY_GENRE: dict = {
    "Pop": [
        {"name": "Taylor Swift",   "related": ["Ed Sheeran", "Ariana Grande", "Olivia Rodrigo"]},
        {"name": "Ariana Grande",  "related": ["The Weeknd", "Dua Lipa", "Taylor Swift"]},
        {"name": "Ed Sheeran",     "related": ["Taylor Swift", "Harry Styles"]},
        {"name": "Dua Lipa",       "related": ["Ariana Grande", "Lizzo", "Harry Styles"]},
        {"name": "The Weeknd",     "related": ["Drake", "Frank Ocean", "Ariana Grande"]},
        {"name": "Harry Styles",   "related": ["Taylor Swift", "Ed Sheeran", "Dua Lipa"]},
        {"name": "Olivia Rodrigo", "related": ["Taylor Swift", "Billie Eilish"]},
        {"name": "Billie Eilish",  "related": ["Olivia Rodrigo", "Lorde"]},
        {"name": "Lizzo",          "related": ["Dua Lipa", "Beyoncé"]},
        {"name": "Lorde",          "related": ["Billie Eilish", "Lana Del Rey"]},
    ],
    "Rock": [
        {"name": "Radiohead",                "related": ["Arctic Monkeys", "Tame Impala", "Muse"]},
        {"name": "Arctic Monkeys",           "related": ["Radiohead", "The Strokes", "Interpol"]},
        {"name": "Nirvana",                  "related": ["Foo Fighters", "Pearl Jam", "Soundgarden"]},
        {"name": "Foo Fighters",             "related": ["Nirvana", "Red Hot Chili Peppers"]},
        {"name": "Red Hot Chili Peppers",    "related": ["Foo Fighters", "Pearl Jam"]},
        {"name": "The Strokes",              "related": ["Arctic Monkeys", "Interpol", "LCD Soundsystem"]},
        {"name": "Pearl Jam",                "related": ["Nirvana", "Soundgarden"]},
        {"name": "Muse",                     "related": ["Radiohead", "Coldplay"]},
        {"name": "Coldplay",                 "related": ["Muse", "U2"]},
        {"name": "Interpol",                 "related": ["The Strokes", "Editors"]},
    ],
    "Electronic": [
        {"name": "Daft Punk",    "related": ["Justice", "Disclosure", "Phoenix"]},
        {"name": "Aphex Twin",   "related": ["Boards of Canada", "Autechre"]},
        {"name": "Four Tet",     "related": ["Caribou", "Jon Hopkins", "Floating Points"]},
        {"name": "Disclosure",   "related": ["Daft Punk", "Jamie xx", "Flume"]},
        {"name": "Flume",        "related": ["Disclosure", "Kaytranada"]},
        {"name": "Jamie xx",     "related": ["Disclosure", "Four Tet"]},
        {"name": "Bicep",        "related": ["Four Tet", "Jon Hopkins"]},
        {"name": "Jon Hopkins",  "related": ["Four Tet", "Bicep", "Brian Eno"]},
        {"name": "Caribou",      "related": ["Four Tet", "Bonobo"]},
        {"name": "Bonobo",       "related": ["Caribou", "Floating Points"]},
    ],
    "Hip-Hop": [
        {"name": "Kendrick Lamar",   "related": ["J. Cole", "Frank Ocean", "Tyler, the Creator"]},
        {"name": "Drake",            "related": ["The Weeknd", "Travis Scott", "Lil Wayne"]},
        {"name": "J. Cole",          "related": ["Kendrick Lamar", "Jay-Z", "Drake"]},
        {"name": "Tyler, the Creator", "related": ["Frank Ocean", "Kendrick Lamar", "Earl Sweatshirt"]},
        {"name": "Travis Scott",     "related": ["Drake", "Future", "Kid Cudi"]},
        {"name": "Jay-Z",            "related": ["Kanye West", "Nas", "J. Cole"]},
        {"name": "Kanye West",       "related": ["Jay-Z", "Kid Cudi", "Frank Ocean"]},
        {"name": "Frank Ocean",      "related": ["Tyler, the Creator", "The Weeknd", "SZA"]},
        {"name": "Earl Sweatshirt",  "related": ["Tyler, the Creator", "MF DOOM"]},
        {"name": "MF DOOM",          "related": ["Earl Sweatshirt", "Madlib"]},
    ],
    "R&B": [
        {"name": "SZA",            "related": ["Frank Ocean", "Erykah Badu", "H.E.R."]},
        {"name": "Daniel Caesar",  "related": ["Frank Ocean", "H.E.R.", "Brent Faiyaz"]},
        {"name": "H.E.R.",         "related": ["SZA", "Jhené Aiko", "Daniel Caesar"]},
        {"name": "Beyoncé",        "related": ["Rihanna", "Alicia Keys", "SZA"]},
        {"name": "D'Angelo",       "related": ["Erykah Badu", "Maxwell", "Anderson .Paak"]},
        {"name": "Erykah Badu",    "related": ["D'Angelo", "Maxwell", "SZA"]},
        {"name": "Jhené Aiko",     "related": ["H.E.R.", "SZA", "Daniel Caesar"]},
        {"name": "Anderson .Paak", "related": ["Kendrick Lamar", "Bruno Mars", "D'Angelo"]},
        {"name": "Brent Faiyaz",   "related": ["Daniel Caesar", "Frank Ocean"]},
        {"name": "Maxwell",        "related": ["D'Angelo", "Erykah Badu"]},
    ],
    "Indie": [
        {"name": "Tame Impala",      "related": ["Radiohead", "Mac DeMarco", "Khruangbin"]},
        {"name": "Mac DeMarco",      "related": ["Tame Impala", "Car Seat Headrest"]},
        {"name": "Phoebe Bridgers",  "related": ["Boygenius", "Julien Baker", "Lucy Dacus"]},
        {"name": "Bon Iver",         "related": ["Fleet Foxes", "The National", "Sufjan Stevens"]},
        {"name": "Fleet Foxes",      "related": ["Bon Iver", "Father John Misty"]},
        {"name": "The National",     "related": ["Bon Iver", "Sufjan Stevens"]},
        {"name": "Vampire Weekend",  "related": ["Arcade Fire", "Tame Impala"]},
        {"name": "Arcade Fire",      "related": ["Vampire Weekend", "LCD Soundsystem"]},
        {"name": "Khruangbin",       "related": ["Tame Impala", "Bonobo", "Leon Bridges"]},
        {"name": "Car Seat Headrest", "related": ["Mac DeMarco", "Alex G"]},
    ],
    "Jazz": [
        {"name": "Miles Davis",        "related": ["John Coltrane", "Herbie Hancock", "Bill Evans"]},
        {"name": "John Coltrane",      "related": ["Miles Davis", "Charles Mingus", "Thelonious Monk"]},
        {"name": "Herbie Hancock",     "related": ["Miles Davis", "Chick Corea"]},
        {"name": "Bill Evans",         "related": ["Miles Davis", "Keith Jarrett"]},
        {"name": "Thelonious Monk",    "related": ["Miles Davis", "Charles Mingus"]},
        {"name": "Kamasi Washington",  "related": ["Flying Lotus", "Kendrick Lamar", "Thundercat"]},
        {"name": "Norah Jones",        "related": ["Diana Krall", "Madeleine Peyroux"]},
        {"name": "Flying Lotus",       "related": ["Kamasi Washington", "Thundercat", "Aphex Twin"]},
        {"name": "Thundercat",         "related": ["Flying Lotus", "Kamasi Washington", "Kendrick Lamar"]},
        {"name": "Floating Points",    "related": ["Four Tet", "Caribou", "Kamasi Washington"]},
    ],
    "Metal": [
        {"name": "Metallica",         "related": ["Megadeth", "Slayer", "Black Sabbath"]},
        {"name": "Tool",              "related": ["A Perfect Circle", "System of a Down", "Mastodon"]},
        {"name": "Black Sabbath",     "related": ["Metallica", "Iron Maiden", "Ozzy Osbourne"]},
        {"name": "Iron Maiden",       "related": ["Black Sabbath", "Judas Priest"]},
        {"name": "Slipknot",          "related": ["System of a Down", "Korn", "Disturbed"]},
        {"name": "System of a Down",  "related": ["Slipknot", "Tool", "Rage Against the Machine"]},
        {"name": "Mastodon",          "related": ["Tool", "Opeth", "Baroness"]},
        {"name": "Opeth",             "related": ["Mastodon", "Tool", "Porcupine Tree"]},
    ],
    "Classical": [
        {"name": "Ludwig van Beethoven",    "related": ["Wolfgang Amadeus Mozart", "Franz Schubert"]},
        {"name": "Wolfgang Amadeus Mozart", "related": ["Ludwig van Beethoven", "Joseph Haydn"]},
        {"name": "Johann Sebastian Bach",   "related": ["George Frideric Handel", "Dietrich Buxtehude"]},
        {"name": "Frédéric Chopin",         "related": ["Franz Liszt", "Robert Schumann"]},
        {"name": "Claude Debussy",          "related": ["Maurice Ravel", "Erik Satie"]},
        {"name": "Pyotr Tchaikovsky",       "related": ["Sergei Rachmaninoff", "Dmitri Shostakovich"]},
        {"name": "Johann Strauss II",       "related": ["Pyotr Tchaikovsky", "Wolfgang Amadeus Mozart"]},
        {"name": "Erik Satie",              "related": ["Claude Debussy", "Maurice Ravel"]},
    ],
    "Country": [
        {"name": "Johnny Cash",      "related": ["Waylon Jennings", "Willie Nelson"]},
        {"name": "Dolly Parton",     "related": ["Kenny Rogers", "Emmylou Harris"]},
        {"name": "Tyler Childers",   "related": ["Sturgill Simpson", "Zach Bryan", "Colter Wall"]},
        {"name": "Zach Bryan",       "related": ["Tyler Childers", "Morgan Wallen"]},
        {"name": "Willie Nelson",    "related": ["Johnny Cash", "Kris Kristofferson"]},
        {"name": "Sturgill Simpson", "related": ["Tyler Childers", "Colter Wall"]},
        {"name": "Colter Wall",      "related": ["Tyler Childers", "Sturgill Simpson"]},
        {"name": "Kacey Musgraves",  "related": ["Zach Bryan", "Dolly Parton"]},
    ],
    "Latin": [
        {"name": "Bad Bunny",    "related": ["J Balvin", "Anuel AA", "Rosalía"]},
        {"name": "J Balvin",     "related": ["Bad Bunny", "Maluma", "Ozuna"]},
        {"name": "Shakira",      "related": ["Jennifer Lopez", "Maluma"]},
        {"name": "Rosalía",      "related": ["Bad Bunny", "J Balvin", "Arca"]},
        {"name": "Peso Pluma",   "related": ["Bad Bunny", "Natanael Cano"]},
        {"name": "Cardi B",      "related": ["Bad Bunny", "J Balvin"]},
    ],
    "K-Pop": [
        {"name": "BTS",       "related": ["BLACKPINK", "EXO", "GOT7"]},
        {"name": "BLACKPINK", "related": ["BTS", "TWICE", "aespa"]},
        {"name": "NewJeans",  "related": ["IVE", "aespa", "BLACKPINK"]},
        {"name": "IVE",       "related": ["NewJeans", "BLACKPINK", "LE SSERAFIM"]},
        {"name": "aespa",     "related": ["NewJeans", "IVE", "BLACKPINK"]},
        {"name": "BIGBANG",   "related": ["BTS", "EXO", "SHINee"]},
    ],
    "Folk": [
        {"name": "Nick Drake",        "related": ["Elliott Smith", "Iron & Wine", "Sufjan Stevens"]},
        {"name": "Sufjan Stevens",    "related": ["Bon Iver", "The National", "Nick Drake"]},
        {"name": "Iron & Wine",       "related": ["Nick Drake", "Fleet Foxes"]},
        {"name": "Simon & Garfunkel", "related": ["Bob Dylan", "Nick Drake"]},
        {"name": "Bob Dylan",         "related": ["Simon & Garfunkel", "Neil Young", "Johnny Cash"]},
        {"name": "Joni Mitchell",     "related": ["Bob Dylan", "Carole King", "Neil Young"]},
        {"name": "Neil Young",        "related": ["Bob Dylan", "Joni Mitchell"]},
    ],
    "Blues": [
        {"name": "B.B. King",          "related": ["Muddy Waters", "Robert Johnson"]},
        {"name": "Muddy Waters",       "related": ["B.B. King", "Howlin' Wolf"]},
        {"name": "Robert Johnson",     "related": ["Muddy Waters", "B.B. King"]},
        {"name": "Gary Clark Jr.",     "related": ["B.B. King", "Jimi Hendrix"]},
        {"name": "John Lee Hooker",    "related": ["Muddy Waters", "B.B. King"]},
    ],
    "Soul": [
        {"name": "Marvin Gaye",    "related": ["Stevie Wonder", "Al Green", "Curtis Mayfield"]},
        {"name": "Stevie Wonder",  "related": ["Marvin Gaye", "Prince", "Al Green"]},
        {"name": "Aretha Franklin", "related": ["Marvin Gaye", "Etta James"]},
        {"name": "Al Green",       "related": ["Marvin Gaye", "Otis Redding"]},
        {"name": "Otis Redding",   "related": ["Al Green", "Sam Cooke"]},
        {"name": "Prince",         "related": ["Stevie Wonder", "Michael Jackson", "D'Angelo"]},
        {"name": "Michael Jackson", "related": ["Prince", "Beyoncé"]},
    ],
    "Ambient": [
        {"name": "Brian Eno",          "related": ["Harold Budd", "Jon Hopkins"]},
        {"name": "Harold Budd",        "related": ["Brian Eno", "Stars of the Lid"]},
        {"name": "Stars of the Lid",   "related": ["Harold Budd", "Grouper"]},
        {"name": "Grouper",            "related": ["Stars of the Lid", "William Basinski"]},
        {"name": "William Basinski",   "related": ["Grouper", "Stars of the Lid"]},
        {"name": "Ólafur Arnalds",     "related": ["Nils Frahm", "Jon Hopkins"]},
        {"name": "Nils Frahm",         "related": ["Ólafur Arnalds", "Brian Eno"]},
    ],
}
